### PR TITLE
Add Saving music for color GUI

### PR DESCRIPTION
**Pull request by TheRealMoeder**

### CODE REVIEW

**Comment by TheRealMoeder** [comment]
It's played whenever you need to press save (b&w)  /ok(color) or else the changes will not be saved, in mixer setup. Changing for example transmitter configuration  gets always saved when exiting the menu, so we have to differentiate. Either this or we completely remove play music saving for all screens

**Comment by F-D-R** [comment]
But still, those changes are not yet saved then.
I don't see too much value in that, because the problem usually is that some people doesn't recognize there is a Save/OK button at all, so they exit without saving...

**Comment by TheRealMoeder** [comment]
I agree, shouldn't we then do the opposite and remove MUSIC_SAVING from B&W screens as well?

**Comment by F-D-R** [comment]
If you ask me, yes we should, just to be consistent across the whole Devo line...

**Comment by TheRealMoeder** [comment]
Agreed.

**Pull request closed without merging**
