### PR TITLE
rework the way to expose protocol data

### PR DESCRIPTION
**Pull request by howard0su**
Use an array Protocols to expose various data to avoid big switch in the code.

This saves another 492bytes from devo7e build.

### CODE REVIEW

**Comment by howard0su** [comment]
Fixed in the latest change.

**Comment by howard0su** [comment]
I plan to buy a devo7e so that I can test by myself.

**Comment by howard0su** [comment]
anyway, Just bought a second hand dev7e which only costs me $25.

**Comment by howard0su** [comment]
devo7e cannot do binding. need fix. please hold.

**Comment by howard0su** [comment]
Verified on devof12e and devo7e. I think this is ready to go.

**Comment by howard0su** [comment]
@hexfet can you enable modular build for t8sg with HAS_EXTENDED_TELEMETRY=1? I think you should be able to do so after apply PR #465.

**Comment by hexfet** [comment]
I made a modular build for T8+ since my T8 is in pieces.   Here's the [changeset](https://github.com/DeviationTX/deviation/compare/master...hexfet:t8sg_plus_modular).  The build is limited to 128K ROM to match builds for limited memory transmitters.

Even with full ROM size enabling extended telemetry for the modular build fails because then some protocols won't fit into 4K of RAM.  DSM and FrskyX are two examples.

**Comment by howard0su** [comment]
i see. i worked a change for f12e to enable 8K RAM for modules. anyway, i think I understand your intention here.

**Pull request merged**
