### PR TITLE
Minor Hungarian language changes

### PR DESCRIPTION
**Pull request by F-D-R**

### CODE REVIEW

**Comment by F-D-R** [comment]
How to create separate pull request for each commit?

**Comment by goebish** [comment]
Create one branch (from master) per pull request.

**Comment by F-D-R** [comment]
OK, how can I do it, when I've already committed both into the master branch? :)

**Comment by goebish** [comment]
That's too late then.
As a rule of thumb, you should never work on the master branch but create a new branch from master each time you start to work on something.

**Comment by F-D-R** [comment]
Well, then I need someone to accept it on one...  :)
Thanks!

**Comment by goebish** [comment]
Are you using a GIT GUI ?
I've been using SourceTree (Mac / Win only ...) for a few years, it's very convenient to manage multiple projects, branches and remotes.

**Comment by F-D-R** [comment]
No, I just use the command prompt on the client side, and the github site for the pull requests...

**Pull request merged**
