### PR TITLE
Cleanup USB stack to save some ROM

### PR DESCRIPTION
**Pull request by howard0su**
1. Split out USB_Enable from [MSC|HID]_Enable
2. Remove some duplicate code
3. remove the array EpInt_IN/OUT.

### CODE REVIEW

**Comment by howard0su** [comment]
after couple of try to integrate usb lib of libopencm3, I finally decide to stay with our current implementation.

the libopencm3 lib is 1KB smaller due to lack of MSC bulk transfer support. In the same time, the memory usage is about 4KB larger than current usb stack. I tried couple of methods to reduce it. But turns out without big rewrite, it is hard to reduce the memory usage.

So I decided to go back and optimize our current stack to get some additional ROM & RAM saving.

For your reference (stats on devo7e):
integrating libopencm3 usb + umass +hid
ROM: 0x08003000 - 0x0801f228 = 112.54kB
RAM: 0x20000000 - 0x2000379c =  13.90kB

what we are today:
ROM: 0x08003000 - 0x0801f61c = 113.53kB
RAM: 0x20000000 - 0x20002714 =   9.77kB

**Comment by PhracturedBlue** [comment]
This is a lot of work for 100bytes of ROM.  The only thing I'm wary of is the changes to usb_conf.h and usb_istr.c.  These changes make it harder to diff against the reference implementation which in turn makes it harder for us to pull in a new reference implementation should we ever want to in the future.

**Comment by PhracturedBlue** [comment]
I see from your other PR that you intend to do a lot of work to the USB drivers, so I'm not going to sweat the little things.

**Comment by howard0su** [comment]
Please review again. I keep the USB lib code untouched this time.

**Pull request merged**
