### PR TITLE
CRSF updates for ELRS

### PR DESCRIPTION
**Pull request by hexfet**
* Add protocol ELRS. Same source code as CRSF but with serial datarate 1.87Mbps
* Add CRSF model match message. Set fixed id 0-63 to use model match.
* Add support for ELRS info message.  Popup dialog when Model Mismatch reported.  The ELRS info message is only requested when disarmed so as not to interfere with stick packets during flight.
* Workaround for glitch when scrolling non-selectable items
* Serial send and receive refactored with additional buffer layer to handle higher data rate

### CODE REVIEW

**Comment by phobos-** [comment]
This is awesome work @hexfet . I am testing it and so far so good! 👍

**Comment by hexfet** [comment]
Thanks!  Appreciate the testing @phobos- .  Just made a PR to ELRS that helps with the UART errors if you could try it.

**Comment by howels** [comment]
@hexfet is this working with the OPENTX_SYNC feature in expressLRS?

**Comment by hexfet** [comment]
@howels Yes, PRs #1018 and #1019 brought in support for the sync packets.

**Comment by hexfet** [comment]
Tested by deviationtx.com user mooiweertje and myself.

**Pull request merged**
