### PR TITLE
Update lang.fr

### PR DESCRIPTION
**Pull request by Morlacus**
dditions to the French lanquage file. May be some texts I added are too long. I do not know if there is a limit. I corrected 2 entries which were wrong and changed 'low rate' in 'petit déb' instead of 'grand déb' and 'high rate' in 'grand déb' instead of 'petit déb'. This could puzzle french users which have already the current translation.

### CODE REVIEW

**Comment by goebish** [comment]
I'd rather use "taux haut" and "taux bas"

**Comment by Morlacus** [comment]
In French we speak of "Débattements" (Déb)  for the travel   of a control surface. As concerns D/R the standard spelling are "grand", "moyen" and "petit" "débattement" The original translation were correct except an inversion between high and low which were not congruent with the english.

**Comment by goebish** [comment]
Ok, I'm French but I always set my stuffs to English language, so you're probably right ;)
However, I'll check with the emulators to make sure string lengths aren't an issue.

**Comment by Morlacus** [comment]
Ok thanks . There is one translation for which I am not very satisfied. It is for Toggle. I tried Basculant but there is possibly better translations. If the string is not too long, Icône basculant or Icône basc would may be better.

**Pull request merged**
