### PR TITLE
Minor changes to enable portability to atmega

### PR DESCRIPTION
**Pull request by pascallanger**

### CODE REVIEW

**Comment by mwm** [comment]
More information, please. Like which Atmega cpu are we looking at. And is there some longer-term goal here?

**Comment by pascallanger** [comment]
PB and victzh contcated me to merge our efforts to develop protocols. I'm therefore trying to change the Multiprotocol code (https://github.com/pascallanger/DIY-Multiprotocol-TX-Module) to work directly with the deviation protocols. The long term goal is to share them and we all contribute to make them better. Today improvements are done in both sides but are not backported...
- Pascal

**Comment by mwm** [comment]
In that case, it might be better to put the protocols in a submodule repository that the two projects can pull in.

**Comment by pascallanger** [comment]
Yes that the long term plan but as a first step I need the to make a couple of changes to be able to  compile everything. Changes that have no impact on your side.

**Comment by victzh** [comment]
Pascal, have you checked why dsm2 can't compile for Devo 7E? Probably not only dsm2. Check this Travis page for detailed log: https://travis-ci.org/DeviationTX/deviation/jobs/130180273

**Comment by victzh** [comment]
Pascal, I managed to merge this pull request in my local repo and build it for Devo 7E. I will test it a bit and push it as a branch - it required regrouping the code a bit.

I merged couple of conflicts - you and goebish edited one file together.

Also, can you set your editor so that tabs will be written as 4 spaces in files, we don't use tabs.

**Pull request merged**
