### PR TITLE
Speedup travis builds

### PR DESCRIPTION
**Pull request by TheRealMoeder**
Some small changes to travis.yml to speed up builds a little:

1. git clone only shallow
2. omit apt-get update
3. git needs no update through apt
4. move away from docker container to trusty VM, as docker containers are phased out anyways by travis
5. set minimal language, as we only need a very basic environment

### CODE REVIEW

**Comment by TheRealMoeder** [comment]
I also experimented with moving to the newer xenial environment, but this no longer includes mingw32 but mingw64, so some deeper changes would be required, for which I can‘t really see and advantages right now.

**Comment by TheRealMoeder** [comment]
Total build time is about 25 % less at the current workload compared to master. But actually the gain is less, as the VM boots slower and this is not counted to the build time, so we cannot really measure it.

**Comment by PhracturedBlue** [comment]
regardless of anything else we do, I see no reason not to speed up the build this way

**Comment by TheRealMoeder** [comment]
Sorry, last commit had wrong syntax and interesting enough happened to stop travis working without and error message. I already pushend a commit to fix this.

**Pull request merged**
