### PR TITLE
Implement CRSFshot synchronization between tx and radio

### PR DESCRIPTION
**Pull request by hexfet**
Use CRSFshot "offset" telemetry to synchronize packet sends with the
transmitter module.  This reduces latency by delivering data to the
transmitter in sync with when the transmitter will use it.

Prior to this change a Crossfire TX LCD shows "CRSF V2" for the RC
Input.  After this change the display is "CRSFshot".

### CODE REVIEW

**Comment by hexfet** [comment]
@phobos- @harlock00999 please test when you have a chance

**Comment by harlock00999** [comment]
@hexfet I'll be glad to help but I'm not sure how, I'm a user, I'm not able to manage code by myself yet. If you give me a build to flash on my radio no problem. If you wanna tell how to do it, I'm here.

**Comment by hexfet** [comment]
No worries.  I"ve uploaded a [test build here](https://deviationtx.com/downloads-new/category/2832-hexfet-crsf-test).

**Comment by harlock00999** [comment]
Great, Thanks! I'm going to test it asap! I'll keep you posted.

**Comment by harlock00999** [comment]
Sorry to bother you again but before flashing the test build I was checking the menus and I cannot fine the "CRSF V2" anywhere. I pretty sure I cheched every spot. I'm currently using the f04bc27. 

I'm going to flash anyway and see if something change. Any tips will be appreciated.

**Comment by hexfet** [comment]
It's just "CRSF" name in Deviation.  It has been version V2.  With #1018 and this PR the CRSFshot features are supported, but there's no new protocol to select.

**Comment by phobos-** [comment]
@hexfet I tested with your test build - for me sync worked perfectly, but I stopped receiving telemetry sensors - attitude and battery. I then built my own firmware from this branch and it worked perfectly.
[deviation-t8sg_v2_plus-v5.0.0-c5c85e5.zip](https://github.com/DeviationTX/deviation/files/7841750/deviation-t8sg_v2_plus-v5.0.0-c5c85e5.zip)
[deviation-t8sg_v2-v5.0.0-c5c85e5.zip](https://github.com/DeviationTX/deviation/files/7841751/deviation-t8sg_v2-v5.0.0-c5c85e5.zip)

**Comment by hexfet** [comment]
@phobos- Thanks!  The test build also includes the changes from #1020 , though none of those changes should break telemetry.  Would you please build that branch and see if it breaks telemetry also?

**Comment by harlock00999** [comment]
@hexfet  I've just tested and on my t8sgv2+ with HGLRC TX2.4 module ERLS2.0 everything seems to work just fine. Telemetry monitor page on the radio is full of information, I can even see my fly mode, did know that.  Same in my OSD. 

What's next? Am I good to go with this build or should I try the @phobos- 's last too?

btw, is there a legend or something for the telemtry monitor of the readio? Some values are obvious other not (for me of course^^)

**Comment by phobos-** [comment]
@harlock00999 if it's working for you then no need to flash my build. Missing telemetry is most likely caused by some configuration error at my end.

**Review by phobos- — APPROVED** [review]

**Comment by harlock00999** [comment]
Perfect! Thanks.

The one thing I noticed though is the delay if I change fly mode: from the activation of the switch to the refresh of the telemery monitor on the radio about 5sec.

**Comment by hexfet** [comment]
> btw, is there a legend or something for the telemtry monitor of the readio? Some values are obvious other not (for me of course^^)

@harlock00999 Section 10.52 of the [user manual](https://deviationtx.com/user-manual/user-manual-7e-10) has a table showing what telemetry values are in each box.  What the values mean should be in the module documentation :)

Thanks for testing!

**Pull request merged**
