### PR TITLE
Reduce ROM usage of music module

### PR DESCRIPTION
**Pull request by howard0su**
1. Parse the name of tone instead of a table.
2. Only store one scale of freq and caculate others.

### CODE REVIEW

**Comment by howard0su** [comment]
Don't know how to test this. The ROM size saving is noticable:

Before:
ROM: 0x08003000 - 0x0801fdb0 = 115.42kB
RAM: 0x20000000 - 0x200028a0 =  10.16kB

After:
ROM: 0x08003000 - 0x0801fc78 = 115.12kB
RAM: 0x20000000 - 0x200028a0 =  10.16kB

**Comment by howard0su** [comment]
verified on 7e, at least startup music works fine.

**Comment by howard0su** [comment]
maybe we should have a longer music for startup. it is fine to compose music like that.

**Comment by TheRealMoeder** [comment]
> maybe we should have a longer music for startup. it is fine to compose music like that.

Every user is open to do so. Feel free to compose a deviation theme if you wish ;-)

**Pull request merged**
