### PR TITLE
Cleanup variable declaration

### PR DESCRIPTION
**Pull request by howard0su**
Make sure we only declare variables in header files. Move allocation to .c file. Also declare the local variables with "static".

### CODE REVIEW

**Comment by howard0su** [comment]
@goebish can u help testing the change 9c0c37c as I don't have hardware to do so. This trick can help reduce the ROM size about 50bytes. I can see such practice in many protocols. We need consider to fix it.

**Comment by goebish** [comment]
I tested with a Blade Inductrix, it works but default channel order is incorrect (probably not because of this PR), it should be TAER for DSM2/X but it's AETR now:
https://imgur.com/a/3pUC3gO

**Comment by howard0su** [comment]
I can be caused by my other change on channel mapping. let me check.

**Comment by goebish** [comment]
After resetting the model it's defaulting to EATR now, which is still wrong.

**Comment by howard0su** [comment]
cannot find obvious error. both dsm code and protocol.c code looks correct. need debug further.

**Comment by goebish** [comment]
I confirm that a version dating from 1 week ago have correct channel mapping for DSM2/DSMX.

**Comment by howard0su** [comment]
I think i know why. Original the channel map doesn't require load the module. After my change, the channel map have to be loaded from module. In module configuration menu, we select DSMX then exit from the menu. The module is *not* loaded at all. So the channel map is incorrect. If you do BIND in the menu, the channel mapping is correct then.

We cannot delay load the module. Let me think about how to fix this.

**Comment by howard0su** [comment]
check #504 which should fix channel map problem.

**Pull request merged**
