### PR TITLE
Add devo12-XMS target

### PR DESCRIPTION
**Pull request by vladislavy**

### CODE REVIEW

**Comment by F-D-R** [comment]
Couldn't we just detect the flash size and work according to the result?

**Comment by vladislavy** [comment]
In that case all devo12 specific code need to be included to common code, and other significant changes. I don't think it will be worth the result.

**Comment by F-D-R** [comment]
No, I thought in the DEVO 12 specific code, since it has specific memory management anyway, hasn't it?

**Comment by vladislavy** [comment]
I don't understand. devo12-XMS use common code and devo12 replace some common code and add some specific code for media drive, at build time.

**Pull request closed without merging**
