### PR TITLE
Fix mux "beep" for extended audio

### PR DESCRIPTION
**Pull request by vladislavy**
It's related to issue #439

### CODE REVIEW

**Comment by vladislavy** [comment]
We finally has not memory for Devo7e. This change doesn't fit to Devo7e memory.

**Comment by TheRealMoeder** [comment]
That is the reason mux beep was only available in has extended audio

**Comment by Tygrys-1** [comment]
> 
> 
> That is the reason mux beep was only available in has extended audio

It is not a problem to have both mux beep and voice. It is the beep to just do a "beep". As trimmers can do beep whith voice mod enabled I think that the mux beep can also do this.

**Comment by TheRealMoeder** [comment]
This is rather small and we have room for it in the room now. Please rebase to recheck with travis ci

**Comment by TheRealMoeder** [comment]
I just ran the Travis job again, so no need for a rebase. But with 100 bytes it is pretty pricey, to be honest.

**Comment by Tygrys-1** [comment]
This make sense. It should be something doing a "beep".

**Comment by TheRealMoeder** [comment]
MUSIC_KEY_PRESSING isn't defined in the default sound.ini, but MUSIC_MAXLEN has the same default beep in sound.ini as MUSIC_SAVING, so I think we should go for this. As vladislavy doesn't have the branch in his repository anymore, I will close this PR and open a new one.

**Pull request closed without merging**
