### PR TITLE
Fix S-FHSS protocol servo throw

### PR DESCRIPTION
**Pull request by vladislavy**
Tested up to 150%

### CODE REVIEW

**Comment by goebish** [comment]
Do you have a genuine Futaba FHSS transmitter ? 
Looks like this protocol is not working well, with most receivers only the 4 first channels are working.
I've neither a Futaba TX or RX, so I can't help with that ...

**Comment by vladislavy** [comment]
I have Futaba 14SG, but havn't S-FHSS receiver. User Poldi reported that Align R6GF receiver can use all 6 channels.

**Comment by vladislavy** [comment]
What does it mean?

**Comment by goebish** [comment]
Just someone that made a mistake, he posted an empty message referencing this PR in the other PR, I deleted it.

**Pull request merged**
