### PR TITLE
Update to GCC-8-2018-q4-major

### PR DESCRIPTION
**Pull request by howard0su**
Upgrade the compiler to latest arm-none-eabi-gcc from ARM. The current compiler is too old to get any support. The new compiler gives better warnings and potentially leverage some new optimization technology.

### CODE REVIEW

**Comment by howard0su** [comment]
Let's do more testings before merge. I see couple of cases that new compiler can generate wrong code.

**Comment by howard0su** [comment]
submitted PR for docker image:
https://github.com/DeviationTX/deviation-docker/pull/2

**Comment by howard0su** [comment]
You can install the compiler for Windows/Linux/OSX here: https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads

Can u get more testings? How can I publish the test firmware to ask community to testing (maybe combined with openlibcm3 change?)?

**Comment by howard0su** [comment]
where can i upload the firmware to host? Can i create a branch and some script to help me do so?

**Comment by TheRealMoeder** [comment]
@PhracturedBlue  or @F-D-R can give you developer permissions for deviationtx so you can upload files to the downloads section using a provided perl script.

**Comment by howard0su** [comment]
there is an interesting bug for LTO in gcc-7: https://bugs.launchpad.net/gcc-arm-embedded/+bug/1747966

maybe LTO is not that stable in gcc.

**Comment by howard0su** [comment]
need update to q4 release which was released at Dec 12.

**Comment by howard0su** [comment]
Interesting, the new compiler generate even smaller file:
GCC-7
devo7e:
ROM: 0x08003000 - 0x0801fd64 = 115.35kB
RAM: 0x20000000 - 0x20002a00 =  10.50kB

devo8:
ROM: 0x08004000 - 0x0803d854 = 230.08kB
RAM: 0x20000000 - 0x2000910c =  36.26kB

GCC-8:
ROM: 0x08003000 - 0x0801fa44 = 114.57kB
RAM: 0x20000000 - 0x20002894 =  10.14kB

ROM: 0x08004000 - 0x0803d6a8 = 229.66kB
RAM: 0x20000000 - 0x20008fac =  35.92kB

**Comment by PhracturedBlue** [comment]
Be really careful with this.  We've had issues in the past with compiler's generating broken code.  I think you should try to move, but definitely should try to get testing on all transmitters you can 1st.

**Comment by howard0su** [comment]
Of course. no rush to get this in. we need more testings.

**Comment by howard0su** [comment]
Can u give me permission to upload test build? Plan to post a test build with new compiler and new libopencm3.

**Comment by PhracturedBlue** [comment]
Done.  I have sent you an email with further instructions

**Comment by howard0su** [comment]
@PhracturedBlue nice report for the size. First time I know the overall picture of the saving by new compiler.

**Comment by howard0su** [comment]
Tested on:
- [ ] devof12e

- [ ] devo12

- [ ] devo7e

- [ ] devo10

**Comment by TheRealMoeder** [comment]
Please force-push again for CI run, thanks!

**Comment by howard0su** [comment]
I plan to get this in next monday with the change in docker https://github.com/DeviationTX/deviation-docker/pull/4 Do you think this is proper @PhracturedBlue @hexfet @TheRealMoeder ?

**Pull request merged**
