### PR TITLE
Add threshold before triggering alarm beep/voice

### PR DESCRIPTION
**Pull request by TheRealMoeder**

### CODE REVIEW

**Comment by vladislavy** [comment]
I don't know how it works, but it doesn't fit to "text" GUI "Telemetry Config" page. I don't sure it can be fitted to Devo F7 (LCD_WIDTH 24).

**Comment by vladislavy** [comment]
src/pages/text/telemconfig_page.c
```
...
#if LCD_WIDTH == 66
//devof12e
enum {
    LABEL_X    = 0,
    LABEL_W    = 2*ITEM_SPACE,
    TEXTSEL1_X = 3*ITEM_SPACE,
    TEXTSEL1_W = 7*ITEM_SPACE,
    TEXTSEL2_X = 12*ITEM_SPACE,
    TEXTSEL2_W = 3*ITEM_SPACE,
    TEXTSEL3_X = 17*ITEM_SPACE,
    TEXTSEL3_W = 9*ITEM_SPACE,
    MSG_X      = 10*ITEM_SPACE,
    MSG_Y      = 5*ITEM_SPACE,
};
#else
enum {
    LABEL_X    = 0,
    LABEL_W    = 1*ITEM_SPACE,
    TEXTSEL1_X = 2*ITEM_SPACE,
    TEXTSEL1_W = 7*ITEM_SPACE,
    TEXTSEL2_X = 11*ITEM_SPACE,
    TEXTSEL2_W = 3*ITEM_SPACE,
    TEXTSEL3_X = 16*ITEM_SPACE,
    TEXTSEL3_W = 7*ITEM_SPACE,
    MSG_X      = 10*ITEM_SPACE,
    MSG_Y      = 5*ITEM_SPACE,
};
#endif
...

```
At least most of telemetry values with threshold will fit Devo F7.

**Comment by TheRealMoeder** [comment]
Sorry, I always forget about text gui...I'll take a look at the emulator.

**Comment by vladislavy** [comment]
In src/pages/128x64x1/telemconfig_page.c
#define ALARM_TH_SPACER "@" 
redefined ALARM_TH_SPACER at  src/pages/text/telemconfig_page.c
So, ALARM_TH_SPACER always is "@"
It has to be moved up, before #endif //OVERRIDE_PLACEMENT

**Comment by TheRealMoeder** [comment]
Sorry for the lazy coding and testing! That is what come's from trying to help without having enough spare time ;)

**Comment by TheRealMoeder** [comment]
Anything else keeping this from having approvals? I'm happy to improve the feature.

**Comment by F-D-R** [comment]
Why did the relation field become button based?

**Comment by TheRealMoeder** [comment]
It has been a long time ( since commit 006efde) . You can test the alarm sound when pushing it. I will update the manual accordingly.

**Comment by F-D-R** [comment]
I see, thanks!

**Pull request merged**
