### PR TITLE
Fix "text" GUI "Standard" - "Throttle Hold" page

### PR DESCRIPTION
**Pull request by vladislavy**

### CODE REVIEW

**Comment by TheRealMoeder** [comment]
Why so many separate pull requests? I'd suggest fixing all standard guis and then do one pull request. It may still consist of separate commits.

**Comment by vladislavy** [comment]
I have bad knowledge how it work. Every time it happened by a way I don't expected.

**Comment by goebish** [comment]
- create a local branch for your fixes
- work on this branch, make as much commits as you want
- push this branch to your repo
- make a pull request
- if you make more commits to this branch they will be added to the pull request until it is merged.

**Comment by TheRealMoeder** [comment]
Exactly. I know git can be annoying when new to it, but putting a little effort into learning the git command line (look at the many tutorials on the Internet) really pays out. I've just recently been through this :)

**Comment by goebish** [comment]
I haven't used git command line for years except for a few exceptions.
I'm using SourceTree GUI, very convenient.
https://www.sourcetreeapp.com/

**Comment by TheRealMoeder** [comment]
I develop on a Linux VM, so I prefer command line or the built-in integration of my preferred editor (Atom).

**Pull request merged**
