### PR TITLE
Protocol for TDR Phoenix Mini

### PR DESCRIPTION
**Pull request by goebish**
Add "Phoenix" format option to the MJXq protocol.
Channel 5: arm

This is a clone of the EAchine E010 with altitude hold, same as the E010 protocol it's using XN297L @ 250 kbps and doesn't work well with every nrf24l01 modules.
https://www.deviationtx.com/forum/protocol-development/8314-tdr-phoenix-mini-eachine-e010-clone

I'd like to add a note in the manual/wiki for those XN297L @ 250 kbps (sub)protocols, but I'm not sure how to phrase it without being too technical. To make it short, the xn297(L) has a ~+200 kHz frequency drift compared to the nrf24l01, that's not an issue @ 1 Mbps but with 250 kbps the xn297l has a tighter oscillator accuracy requirement (20ppm vs 60ppm) thus not enough selectivity to cope with this drift sometimes. Success depends only on the (in)accuracy of the oscillators in the tx and rx, you can even have 2 of those quads with one working perfectly while the other does not bind at all.

I should make some tests the other way round, emulating a nrf24l01 with a XN297L, if it works well (there's no reason it doesn't ...) maybe we could tell the 4-in-1 manufacturers to use XN297L instead of nrf24l01 in the future as its base frequency can be fine tuned (same as the 3 other transceivers) and so far we've more xn297 protocols than nrf24l01 anyway. Also, it has an internal PA that can be set to 2 dBm (up to 13 dBm but that would saturate our PA), that would allow 150mW for nrf24l01/xn297 protocols.

### CODE REVIEW

**Comment by goebish** [comment]
On hold because I'm not sure it's set to high rate, I've asked the user to make another capture.

**Comment by alanchan2772** [comment]
Can you put the e010 out of mjxq protocols and add the freq-fine turning to it just like s-fhss protocols! if can not,why?thanks!

**Comment by goebish** [comment]
That's not possible, S-FHSS protocol is using the cc2500 transceiver, on which frequency can be fine tuned.
The mjqx/e010 protocol is using the nrf24l01, this transceiver can't be fine tuned in software.

**Comment by alanchan2772** [comment]
o.i see.Thanks for your help, much appreciated.

**Comment by alanchan2772** [comment]
I ask the nrf24l01 maker (【nRF24L01P+PA+LNA大功率2.4G无线收发模块500mW无人机NRF2401数传】https://m.tb.cn/h.e0NJznx?sm=c9bd91 点击链接，再选择浏览器咑閞；或復·制这段描述￥HV7SYapY3hc￥后到👉淘♂寳♀👈) they said  it can turn the frequence

**Comment by alanchan2772** [comment]
Is that A7105 can be fine turned in sofeware too?

**Comment by goebish** [comment]
He lies, frequency can't be fine tuned in software with a nrf24l01 (see datasheet), and yes the A7105 can be fine tuned in software, as the cyrf6936 and the cc2500.

**Comment by goebish** [comment]
"tuning" and "fine tuning" is not the same thing ;)

**Comment by alanchan2772** [comment]
ok，i see!
I  just want to keep the hope!
Thank you very much!

Thanks all the Deviation team,best wish!

**Comment by goebish** [comment]
I might have found a solution, please see and continue the discussion here:
https://www.deviationtx.com/forum/protocol-development/6307-eachine-e010-inductrix-clone-data-captures?start=280#73920

**Comment by alanchan2772** [comment]
It worked perfectly on my devo 7e，thank you goebish.You are a genius!

**Comment by alanchan2772** [comment]
Can JJRC H31  bind with  devo 7e?If can ,that is  perfect!

**Comment by goebish** [comment]
Thanks for testing, the JJRC H31 isn't on my list yet, sorry ;)

**Comment by alanchan2772** [comment]
Please,please,please! I send the h
31 and controler to you  ,ok?

**Comment by goebish** [comment]
Please open a topic on the forum (protocol development), that's a better place to discuss.

**Comment by alanchan2772** [comment]
My english is limited!
I  i  i  !

**Comment by goebish** [comment]
No worries, it's good enough, but go to the forums ;)
https://www.deviationtx.com/forum/protocol-development

**Comment by alanchan2772** [comment]
Ok
I open a topic on  the forum (protocol development), thanks! Hah

**Comment by alanchan2772** [comment]
Help to find the protocol for JJRC H31 please! 

Help!Help!Help! Help to find the protocol for JJRC H31,Goebish and HappyHarry,please come in!

The JJRC H31 is inexpensive, robust, good flight times, simple and straightforward basic quad to just tool around with. So please! please! please!

**Comment by alanchan2772** [comment]
Sorry , I don't know how to post the picture!

**Pull request merged**
