### PR TITLE
Added dsm rssi telemetry

### PR DESCRIPTION
**Pull request by phobos-**
According to spec published by Spektrum:
https://www.spektrumrc.com/ProdInfo/Files/SPM_Telemetry_Developers_Specs.pdf

packet 7e should contain rssi for antenna a or antenna b.
This pr contains:
- parsing additional 1 byte when telemetry packet is an RPM packet (0x7E).
- adjustments to DSM telemetry screen.

Tested with T8SG V2 Plus and custom betaflight firmware that sends rssi telemetry.
screenshot

### CODE REVIEW

**Comment by githubDLG** [comment]
great job,man!!!!

**Comment by TheRealMoeder** [comment]
TELEMETRY_Alarm() in telemetry.c needs to be updated as well

**Comment by howard0su** [comment]
I suggest we cleanup telemetry a bit. In the ideal world, each different protocol should generate different set of defined telemetry values, which should be common between all protocols with some extension. As today, we have to modify telemetry code every time we have some new telemetry value from the protocols.

For example, we can do this:
enum
{
    TELEM_VOLT = 1,
    TELEM_TEMP = 11,
    TELEM_RPM = 20,
};

enum {
    TELEM_DEVO_VOLT1 = TELEM_VOLT,
    TELEM_DEVO_VOLT2 = TELEM_VOLT + 1,
    TELEM_DEVO_VOLT3 = TELEM_VOLT + 2,
    TELEM_DEVO_TEMP1 = TELEM_TEMP + 1,
    TELEM_DEVO_TEMP2 = TELEM_TEMP  + 2,
...............
}; 

In telemetry.c, we only handle the common defined telemetry values.

**Comment by phobos-** [comment]
@TheRealMoeder thanks for the tips! I am not too familiar with the codebase, could you elaborate more what needs to be changed? Which file refers to color gui?
TELEMETRY_Alarm() works fine, it will just use the defaults. I was able to set up an alarm for rssi in my t8sg. What would be your suggested voice for rssi? Neither frsky nor crsf have anything set up for rssi, so I dont know which VOICE_UNIT_* should I choose.

@howard0su good idea, I'll try to implement it and update the pull request.

**Comment by TheRealMoeder** [comment]
> @TheRealMoeder thanks for the tips! I am not too familiar with the codebase, could you elaborate more what needs to be changed? Which file refers to color gui?

Please adapt deviation/src/pages/320x240x16/telemtest_page.c. Testing the GUI can be easily done using the emulators. Also please check the telemtest_page on text GUI (f7/f12e).

> TELEMETRY_Alarm() works fine, it will just use the defaults. I was able to set up an alarm for rssi in my t8sg. What would be your suggested voice? Neither frsky nor crsf have anything set up for rssi, so I dont know which VOICE_UNIT_* should I choose.

Sorry, I thought I had implemented VOICE_UNIT_DBM. My bad.

**Comment by howard0su** [comment]
> @howard0su good idea, I'll try to implement it and update the pull request.
My suggestion doesn't apply to this PR. you can do it in a separate PR.

**Comment by phobos-** [comment]
Added rssi to color gui:
Devo8

**Comment by TheRealMoeder** [comment]
I just noticed there is actually a VOICE_UNIT_DB implemented

**Comment by phobos-** [comment]
@TheRealMoeder good catch!
Added in #492

**Pull request merged**
