### PR TITLE
 DSM telemetry update #2 

### PR DESCRIPTION
**Pull request by vladislavy**
Fixed all errors that I can find. Changed the sensor names to be shorter (no more than 7 symbols) and more recognizable. Now "Telemetry config" page work fine for all telemetry sensors.

### CODE REVIEW

**Comment by vladislavy** [comment]
Added some additional corrections. I think it's final version.

**Comment by vladislavy** [comment]
Sorry. Forget to delete some comments.

**Comment by vladislavy** [comment]
Upss, I did not know that it will be automatically merged with the previous pull request.

However, it is tested by Deviation Devo7e build with Nine Eagles YAK54 and all works fine.

**Comment by goebish** [comment]
You should create new branches instead of committing to your master branch ;)

**Comment by vladislavy** [comment]
OK, I will try to create new branch next time.

**Pull request merged**
