### PR TITLE
Adding LISTBOX_FONT, and eliminating the global labelDesc font

### PR DESCRIPTION
**Pull request by F-D-R**

### CODE REVIEW

**Comment by vladislavy** [comment]
FDR, even before this commit: if I visit "Telemetry monitor" pages (both pages or two or several times first page), next I try to change model icon, default icon disappeared or not, I walk on icons and emulator eventually crashed. I can't find the reason (emu_devof12e and emu_devo10).

**Comment by F-D-R** [comment]
I don't think it has anything to do with these changes.
I went back to pull request #100 in 14th of january, and it was already wrong then.
I will look for the cause further. The official 5.0.0 hasn't got this but, but back then there was no list on the icon selection, but a textselect field...

**Comment by vladislavy** [comment]
It started after replace Listbox with Scrollable, and crashed only with default icon. If I don't touch default icon, emulator do not crash.
https://github.com/DeviationTX/deviation/commit/db1bef098aefe9a34be34a9f77e44d8570c30dad

**Comment by F-D-R** [comment]
Pushed a temporary solution in #205

**Pull request merged**
