### PR TITLE
Fix compiler warning, ensure welcome message if no splash page, fix emu7e build

### PR DESCRIPTION
**Pull request by TheRealMoeder**

### CODE REVIEW

**Comment by vladislavy** [comment]
There is not sense to have separate case for default, it's only for compiler do not think that possible to have vpt unassigned. At any case VOICE_SRC_MIXER will be default, but compiler don't know about it.

**Comment by TheRealMoeder** [comment]
Updated pull request, I guess this is now the most reasonable and memory sparing approach ;)

**Comment by TheRealMoeder** [comment]
No it won't, because voice even without menu does by far not fit on the 7e, unless we exclude standard mixer gui

**Comment by F-D-R** [comment]
I see, thanks...

**Pull request merged**
