### PR TITLE
Timer-based PPM protocol

### PR DESCRIPTION
**Pull request by hexfet**
Uses timer to generate ppm output pulses, replacing current method of bit-banging based on clock timer callbacks.  This improves control of the pulse width to reduce jitter.

The implementation is based on the timer code that had been commented-out in pwm.c, which needed fixes for defines and co-operation with usart using the same pin.  The basic logic was correct.  Some usart code is also updated for co-operation.

This has been tested with devo10 and t8sg.  Needs devo12 and modular build testing as those are slightly different.  [Test builds available](https://www.deviationtx.com/downloads-new/category/818-hexfet-ppm-timer).

### CODE REVIEW

**Comment by F-D-R** [comment]
I guess we should wait until somebody test this on the 7E/12 then...

**Comment by hexfet** [comment]
Yes, before merging I think.  The 12 uses a different pin for ppm, and the modular build makefile had to be changed to include the libopencm3 library.  Went ahead with the PR for review and comments.

**Comment by TheRealMoeder** [comment]
How exact has testing to be? My scope is not yet with me after moving, I only have the the cheap LA available, which obviously can't do jitter analysis. But if it's just a matter of checking the PPM output, I could test the 7e modular build

**Comment by F-D-R** [comment]
I think that will do for now...

**Comment by hexfet** [comment]
Yes, I think even just testing with the trainer input of another transmitter would be fine.

**Comment by TheRealMoeder** [comment]
Please be patient, I just have not had the time to run the tests yet

**Comment by OpenUAS** [comment]
@TheRealMoeder could you find some time to test @hexfet nice improvement? TIA

**Comment by hexfet** [comment]
I made a modular build for my t8sg to test.  It works fine.  That leaves just the devo12 variation untested.   It would be better to go ahead and merge I think.

**Comment by hexfet** [comment]
There is a problem with this implementation in a modular build. Not sure how my first test worked.  Would like opinions on the best solution.

The issue is with the ISR in target/common/devo/protocol/pwm.c.  In a modular build this code is linked into the protocol .mod file, so the address in the vector table is not correct when the code is run.

One way to fix this would be to set the address in the vector table at runtime when the ppmout protocol is loaded.  But I think this would take some post-processing to find the ISR offset in the .mod file and then patch it somewhere it could be found at runtime.  Or is there an easy way to get a function offset in the .mod file at runtime?

Another option is to move the pwm.c code into the dfu file.  The disadvantage is using more flash in the modular build.  Also I'm not sure how to make it happen in the makefiles.

Are there other options?

**Comment by hexfet** [comment]
Setting the interrupt vector at runtime is not possible because the vector table is stored in flash (so much for late-night programming :/)  I've moved the pwm.c code out of the .mod file which increases the size of the modular builds by 448 bytes, moving from 115.27 to 115.71 KB.

**Comment by hexfet** [comment]
Moved only the timer interrupt service routine and data pointer to rom.  Now the modular build rom memory usage is just 96 bytes more than the master branch.  Test builds are updated.  I've tested both normal and modular builds on t8sg.

**Pull request merged**
