### PR TITLE
Some GUI rework

### PR DESCRIPTION
**Pull request by F-D-R**
Separated the text align from the box type.
Enabled underline type for the color transmitters.
Introduced a label font type.
Converted the labels to the LABEL_FONT.
Some other GUI bug fixes...

### CODE REVIEW

**Comment by vladislavy** [comment]
Devo 10 model setup page has not labels, buttons only.

**Comment by F-D-R** [comment]
It is because you don't have the new [font-label] section in the config.ini, which is included in the source.
I'll see how can I solve the compatibility with old config files...

**Comment by vladislavy** [comment]
Sorry, I forget to copy new config.ini files.

**Comment by vladislavy** [comment]
FDR, I think that after these changes: the "Mixer" page have strange look after visit any "Toggle select" page (devo10 emulator). For Devo F12E the "Mixer" page become totally unusable after that, all labels started with selection symbol (filled >).

**Comment by F-D-R** [comment]
Yes, I read about that in your ultimate F12E thread, and I've already corrected it in #187

**Comment by vladislavy** [comment]
FDR, now I see the same problem with "Channel monitor" page, emu_devof12e.

**Comment by F-D-R** [comment]
OK, I will check it later.
The channel monitor is one of the few pages, which still uses the generic labelDesc styling...

**Comment by F-D-R** [comment]
OK, corrected and sent pull request #195

**Pull request merged**
