### PR TITLE
Fix perl build on Windows

### PR DESCRIPTION
**Pull request by howard0su**

### CODE REVIEW

**Comment by howard0su** [comment]
@goebish reported that perl on windows doesn't support "S<".

**Comment by PhracturedBlue** [comment]
You probably know better than I do.  Is it worth using 2 bytes and manually specifying the order?

**Comment by howard0su** [comment]
Yes, have to. otherwise lang.* cannot fit into 64kb flash with other media.

**Comment by hexfet** [comment]
The byte order modifier works on my Windows perl 5.1.2.  Doesn't make sense a feature like that would be OS dependent.  I don't build deviation on windows though.  What was the failure?

Wouldn't this change mean the file would be different if build on a big-endian machine?  Which may never happen - don't have one myself to test on.

**Comment by goebish** [comment]
It doesn't work on my side, Windows, perl 5.8.8 msys-int64
https://github.com/DeviationTX/deviation/commit/5b3d4214f7cf65d71be3a9ef0e8cd10cabc9ee2e#commitcomment-31830468

**Comment by PhracturedBlue** [comment]
but it should probably be 'CC' (with appropriate casting) instead of 'S' to ensure the endianness?

**Pull request merged**
